<a href="https://colab.research.google.com/github/Jaydale3221/ATM-Analytics/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
#why and what it does?
#1d or 2d arrays
my_list = [1,2,3]
# print(my_list)
import numpy as np
arr = np.array(my_list)
# print(arr)

my_mat = [[1,2,3], [4,5,6]]
print(my_mat)
print(np.array(my_mat))



[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [50]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones(1)

array([1.])

In [6]:
np.ones((1,1))

array([[1.]])

In [7]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [8]:
# one bracket 1 dimensional 2 dimensional will have 2 bracket and 3 will have 3

In [9]:
np.eye(1) #identity metrics

array([[1.]])

In [10]:
#random numbers

In [11]:
np.random.rand(2)

array([0.72877523, 0.7486134 ])

In [12]:
np.random.rand(2,2)

array([[0.40599981, 0.96803871],
       [0.43167036, 0.71468315]])

In [13]:
np.random.rand(2,2)

array([[0.71046535, 0.39213705],
       [0.22172013, 0.80981209]])

In [14]:
np.random.randn(2,2)

array([[-0.35943661,  0.88774561],
       [ 1.15304119,  0.23379275]])

In [15]:
np.random.randint(1,100,10)

array([87, 20, 12,  8, 78, 71, 25, 83, 24, 51])

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
ranarr = np.random.randint(0,50,10)

In [19]:
ranarr

array([10, 43, 48, 17, 21, 31,  6, 31, 35, 41])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
#max or min location

In [22]:
ranarr.max()

np.int64(48)

In [23]:
ranarr.min()

np.int64(6)

In [24]:
ranarr

array([10, 43, 48, 17, 21, 31,  6, 31, 35, 41])

In [25]:
ranarr.argmax()

np.int64(2)

In [26]:
ranarr.argmin()

np.int64(6)

In [27]:
ranarr.reshape(1,10)

array([[10, 43, 48, 17, 21, 31,  6, 31, 35, 41]])

In [28]:
#practice

In [29]:
my_list = [1,2,3,4]
print(my_list)

[1, 2, 3, 4]


In [30]:
np.array(my_list)

array([1, 2, 3, 4])

In [31]:
lst = [[1,2,3], [4,5,6]]
print(lst)

[[1, 2, 3], [4, 5, 6]]


In [32]:
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [34]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((1,1))

array([[1.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.linspace(0,5,10) # will give 10 output evenly spaced from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [38]:
np.random.rand(1,2)# uniform distribution between 0 and 1

array([[0.34295103, 0.17827525]])

In [39]:
np.random.randn(1,2)# # normal (Gaussian) distribution, mean=0

array([[0.85780215, 0.59303499]])

In [40]:
np.random.randint(2,100,10)

array([30,  9, 69,  9, 95, 34, 27, 89, 50, 48])

In [41]:
arr = np.random.randint(1,100,10)
arr

array([57, 24, 14, 96, 75, 23, 73, 48, 77, 44])

In [42]:
arr.max()

np.int64(96)

In [43]:
arr.argmax()

np.int64(3)

In [71]:
arr
arr.shape

(3,)

In [45]:
arr  + arr

array([114,  48,  28, 192, 150,  46, 146,  96, 154,  88])

In [46]:
arr ** 2

array([3249,  576,  196, 9216, 5625,  529, 5329, 2304, 5929, 1936])

In [47]:
np.sin(arr)

array([ 0.43616476, -0.90557836,  0.99060736,  0.98358775, -0.38778164,
       -0.8462204 , -0.67677196, -0.76825466,  0.99952016,  0.01770193])

In [48]:
np.sqrt(arr)

array([7.54983444, 4.89897949, 3.74165739, 9.79795897, 8.66025404,
       4.79583152, 8.54400375, 6.92820323, 8.77496439, 6.63324958])

In [63]:
np.linspace(1,4,10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [66]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [68]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [69]:
arr.shape()

TypeError: 'tuple' object is not callable